#!/usr/bin/env python3
"""
Generate the placeholder character mesh (assets/simple_box.obj) that
Renderer::Initialize() loads at startup.

This file did not exist anywhere in the repo, so a fresh clone could
configure and compile cleanly but would fail at runtime with
"[Renderer] Failed to load assets/simple_box.obj". This script closes
that gap as part of the asset pipeline.

The mesh is a simple triangulated cube, written in the minimal OBJ
subset that engine::Mesh::LoadFromOBJ understands: "v x y z" vertex
lines and "f a/.. b/.. c/.." triangle faces (no quads, no separate
vt/vn lookups — the parser only reads the position index before the
first '/').

Run locally: python3 scripts/generate_placeholder_mesh.py
"""

from pathlib import Path

ASSETS_DIR = Path(__file__).resolve().parents[1] / "assets"
OUT_FILE = ASSETS_DIR / "simple_box.obj"

# Unit cube, centered on the origin.
VERTICES = [
    (-0.5, -0.5, -0.5),
    (0.5, -0.5, -0.5),
    (0.5, 0.5, -0.5),
    (-0.5, 0.5, -0.5),
    (-0.5, -0.5, 0.5),
    (0.5, -0.5, 0.5),
    (0.5, 0.5, 0.5),
    (-0.5, 0.5, 0.5),
]

# Triangulated faces (1-based indices, OBJ convention). Two triangles
# per cube face, wound consistently (counter-clockwise when viewed
# from outside).
FACES = [
    (1, 2, 3), (1, 3, 4),  # back  (-z)
    (5, 8, 7), (5, 7, 6),  # front (+z)
    (1, 5, 6), (1, 6, 2),  # bottom (-y)
    (4, 3, 7), (4, 7, 8),  # top    (+y)
    (1, 4, 8), (1, 8, 5),  # left   (-x)
    (2, 6, 7), (2, 7, 3),  # right  (+x)
]


def generate():
    ASSETS_DIR.mkdir(parents=True, exist_ok=True)

    lines = [
        "# Placeholder character mesh generated by",
        "# scripts/generate_placeholder_mesh.py — a unit cube standing",
        "# in for real character art until the vertical slice has",
        "# proper assets.",
    ]
    for x, y, z in VERTICES:
        lines.append(f"v {x} {y} {z}")
    for a, b, c in FACES:
        lines.append(f"f {a} {b} {c}")

    OUT_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote placeholder mesh: {OUT_FILE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(generate())
